name: flip-cmd
version: 0.1.0.0
category: Simple
author: aiya000
maintainer: aiya000 <aiya000.develop@gmail.com>
copyright: aiya000
license: MIT
homepage: https://github.com/aiya000/hs-flip-cmd
description: Haskell's flip function in our CLI
synopsis: e.g. `flip systemctl foo.service start` does `systemctl start foo.service`

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-unused-do-bind
  - -Wno-orphans
  - -fprint-potential-instances
  - -fprint-explicit-kinds

dependencies:
  - base >= 4.7 && < 5

executables:
  flip:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
